### ISSUE TITLE
Create Reflections Document

### ISSUE THREAD

**Issue by JoshuaWard9080** [EricHarrison72/gitGoblins#180]
Create the reflections document, which involves answering:

1. How did your project management work for the team?  What was the hardest thing, and what would you do the same/differently the next time you plan to complete a project like this? 

2. Do you feel that your initial requirements were sufficiently detailed for this project?  Which requirements did you miss or overlook

3. What did you miss in your initial planning for the project (beyond just the requirements)?

4. Would you (as a team) deal with testing differently in the future?

5. If you were to estimate the efforts required for this project again, what would you consider?  (Really I am asking the team to reflect on the difference between what you thought it would take to complete the project vs what it actually took to deliver it).   

6. What did your team do that you feel is unique or something that the team is especially proud of (was there a big learning moment that the team had in terms of gaining knowledge of a new concept/process that was implemented).

**Comment by iansteyn** [comment]
Planned to be done as a group in meeting next week
