### ISSUE TITLE
Flask: Set up blueprints

### ISSUE THREAD

**Issue by iansteyn** [EricHarrison72/gitGoblins#78]
Create different blueprints for different parts of the app. Each should be "registered" in a separate `.py` file, which contains the view methods associated with it. (right now we only have one blueprint called _bp_, registered in `views.py`, and all our view methods use it.) 

[Flask Docs tutorial for Blueprints](https://flask.palletsprojects.com/en/3.0.x/tutorial/views/)

**Comment by EricHarrison72** [comment]
Everything so far is set up correctly. With every new .py file for separate webpages we will need to create a new blueprint and import/register it in __init__.py.
